name: bue_rt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.0.3
  firebase_core: ^3.2.0
  hooks_riverpod: ^2.5.1
  syncfusion_flutter_gauges: ^24.2.8
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/
  fonts:
    - family: Digi
      fonts:
        - asset: fonts/ds-digi.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/middle.png'
  remove_alpha_ios: true