// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGlySddWBI-T6TYHDaMq0S8M2hS4mTFg',
    appId: '1:227742441628:web:f7e086ff8fdc0d006bcd59',
    messagingSenderId: '227742441628',
    projectId: 'rt-screen-afa55',
    authDomain: 'rt-screen-afa55.firebaseapp.com',
    databaseURL: 'https://rt-screen-afa55-default-rtdb.firebaseio.com',
    storageBucket: 'rt-screen-afa55.appspot.com',
    measurementId: 'G-SQZ5M6HW4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYcr_hu25eYFJpUnn8K4LeGgF2gfHIxCU',
    appId: '1:227742441628:android:42c8d19c420bf63f6bcd59',
    messagingSenderId: '227742441628',
    projectId: 'rt-screen-afa55',
    databaseURL: 'https://rt-screen-afa55-default-rtdb.firebaseio.com',
    storageBucket: 'rt-screen-afa55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapsfqMhCT0u7ldvNU7ZhSljm7qF-Sbm4',
    appId: '1:227742441628:ios:be75f85025bddaec6bcd59',
    messagingSenderId: '227742441628',
    projectId: 'rt-screen-afa55',
    databaseURL: 'https://rt-screen-afa55-default-rtdb.firebaseio.com',
    storageBucket: 'rt-screen-afa55.appspot.com',
    iosBundleId: 'com.tristans.bueRt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCapsfqMhCT0u7ldvNU7ZhSljm7qF-Sbm4',
    appId: '1:227742441628:ios:be75f85025bddaec6bcd59',
    messagingSenderId: '227742441628',
    projectId: 'rt-screen-afa55',
    databaseURL: 'https://rt-screen-afa55-default-rtdb.firebaseio.com',
    storageBucket: 'rt-screen-afa55.appspot.com',
    iosBundleId: 'com.tristans.bueRt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQGlySddWBI-T6TYHDaMq0S8M2hS4mTFg',
    appId: '1:227742441628:web:abbe11ad1ce3755d6bcd59',
    messagingSenderId: '227742441628',
    projectId: 'rt-screen-afa55',
    authDomain: 'rt-screen-afa55.firebaseapp.com',
    databaseURL: 'https://rt-screen-afa55-default-rtdb.firebaseio.com',
    storageBucket: 'rt-screen-afa55.appspot.com',
    measurementId: 'G-XFQWL8K15P',
  );
}
